### ISSUE TITLE
The Sieve of Eratosthenes.

### ISSUE THREAD

**Issue by dibby-dev** [abirbhattacharya82/DSA#1]
The Sieve of Eratosthenes is a technique that was developed more than 2,000 years ago to find all of the prime numbers easily
between 2 and some limit.
A program that implements this algorithm correctly displays all prime numbers between 2 and a limit entered by the user, say 1,000,000 in a few seconds.

**Comment by abirbhattacharya82** [comment]
The above issue is solved
