### ISSUE TITLE
Search in a Binary Search Tree

### ISSUE THREAD

**Issue by sarthak98tyagi** [abirbhattacharya82/DSA#16]
Given a binary search tree with unique values and a value to be searched, find the node with a given value if no such node exists return null.

**Comment by sarthak98tyagi** [comment]
Hi @abirbhattacharya82 
Please assign this issue to me

**Comment by SoumyadeepMukherjee** [comment]
Kindly assign me this issue

**Comment by Subhadas2000** [comment]
please assign  me this issue

**Comment by abirbhattacharya82** [comment]
the above issue is closed
