### ISSUE TITLE
Plus One

### ISSUE THREAD

**Issue by trojan-coder** [abirbhattacharya82/DSA#6]
## Problem Statements
You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's. <br>
Increment the large integer by one and return the resulting array of digits. <br>
## Example
Input: digits = [1,2,3] <br>
Output: [1,2,4] <br>
Explanation: The array represents the integer 123. <br>
Incrementing by one gives 123 + 1 = 124. <br>
Thus, the result should be [1,2,4]. <br>

**Comment by abirbhattacharya82** [comment]
Problem has been Solved
