### ISSUE TITLE
Length of Last Word

### ISSUE THREAD

**Issue by trojan-coder** [abirbhattacharya82/DSA#7]
## Problem Statement
Given a string s consisting of words and spaces, return the length of the __last__ word in the string. <br>
A __word__ is a maximal substring consisting of non-space characters only.
## Example
Input: s = "Hello World" <br>
Output: 5 <br>
Explanation: The last word is "World" with length 5.

**Comment by abirbhattacharya82** [comment]
The problem has been solved
