### ISSUE TITLE
Search Insert Position

### ISSUE THREAD

**Issue by trojan-coder** [abirbhattacharya82/DSA#8]
## Problem Statement
Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order. <br>
You must write an algorithm with O(log n) runtime complexity. <br>
## Example
Input: nums = [1,3,5,6], target = 5 <br>
Output: 2

**Comment by abirbhattacharya82** [comment]
The Issue has been resolved
