### ISSUE TITLE
Fibonacci Series - C Code missing

### ISSUE THREAD

**Issue by tarunbalajiks** [abirbhattacharya82/DSA#80]
Please assign the task of writing the code in C language for Fibonacci Series.

**Comment by radhika2503** [comment]
please assign this task to me.

**Comment by radhika2503** [comment]
hey I have completed this task Can You merge it Now?
Thank You !

**Comment by Moksh45** [comment]
Please assign the task To me

**Comment by abirbhattacharya82** [comment]
The above issue is resolved
