### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by trojan-coder** [abirbhattacharya82/DSA#9]
## Problem Statement
Write a function to find the longest common prefix string amongst an array of strings. <br>
If there is no common prefix, return an empty string "".
## Example
Input: strs = ["dog","racecar","car"]<br>
Output: ""<br>
Explanation: There is no common prefix among the input strings.<br>

**Comment by abirbhattacharya82** [comment]
The above Issue has been resolved
